Go linter
Hexlet/hexlet-common-images pull request #63
Opened 2023-03-30 10:09 UTC by sgmdlt

2023-04-04 07:46 UTC, corsicanec82 requested changes
В результате нужно чтобы команда make lint-golangci отрабатывала.
А именно выводила ошибки

2023-04-04 07:46 UTC, corsicanec82 commented on golangci-lint/.cache/README
> +This directory holds cached build artifacts from golangci-lint.
вся директория .cache указана в .gitignore, в таком случае её выгружать на гитхаб не требуется.

2023-04-04 07:46 UTC, corsicanec82 commented on golangci-lint/linter
> +/usr/src/linter/bin/golangci-lint run /usr/src/app/...
/usr/src/linter/bin/golangci-lint
сейчас в репе это не работает потому как нет такого пути внутри контейнера.
Используй подход как в других линтерах с переменной LINTER_HOME

2023-04-04 07:46 UTC, corsicanec82 commented on Makefile
> +		-v $(CURDIR)/golangci-lint/.cache:/linter/.cache \
волюм с .cache лучше сделать анонимным, чтобы он не создавался локально
-v /path/to/cache

2023-04-04 07:46 UTC, corsicanec82 commented on golangci-lint/Dockerfile
> +ENV GOLANGCI_LINT_CACHE=/linter/.cache
этой переменной будет мало, придётся побороться ещё с кешем самого go, который по дефолту находится в $HOME/.cache. Для этого пригодится переменная GOCACHE
Для размещения кеша как go, так и самого линтера можно использовать директорию /var/tmp/.cache она будет уникальной для каждого упражнения. Собственно эту директорию и сделай анонимным волюмом

2023-04-12 05:15 UTC, ashikov commented
@sgmdlt тыц

2023-04-17 08:48 UTC, ashikov commented
@sgmdlt есть какой-то прогресс, дружище?

2023-05-29 10:29 UTC, ashikov commented
@sgmdlt идёт дело?))

2023-05-31 16:19 UTC, sgmdlt commented
Отправил новый пр

2023-05-31 16:19 UTC, closed without merging