update flake8
Hexlet/hexlet-common-images pull request #67
Opened 2023-04-25 14:20 UTC by sgmdlt

2023-05-02 03:42 UTC, emp7yhead commented
@corsicanec82 посмотри, пожалуйста

2023-05-02 13:46 UTC, corsicanec82 requested changes

2023-05-02 13:46 UTC, corsicanec82 commented on python-flake8/linter
> +#!/bin/sh
похоже код задублировался

2023-05-02 13:46 UTC, corsicanec82 commented on python-flake8/linter
> -python3 -m flake8 --config=$OUTPUT_CONFIG /usr/src/app
Теперь получается что проверка кода линтером будет осуществляться только при наличии файла setup.cfg в практике?
А если файла нет то не проверяем вообще?

2023-05-02 13:46 UTC, corsicanec82 commented on python-flake8/linter
> +OUTPUT_CONFIG=/tmp/setup.cfg
Далее судя по коду эта переменная в проверке никак не используется. Нужно ли её определять и ниже копировать по этому пути базовый конфиг линтера

2023-05-02 13:46 UTC, corsicanec82 commented on python-flake8/linter
> +  python3 -m flake8 --append-config=$RULESET /usr/src/app
так будет использовать только конфиг который лежит в самой практике. А как быть с базовой конфигурацией, которая лежит в $LINTER_DIR/setup.cfg

2023-05-03 10:25 UTC, sgmdlt commented on python-flake8/linter
> +  python3 -m flake8 --append-config=$RULESET /usr/src/app
Поправил, посмотри

2023-05-03 10:32 UTC, corsicanec82 commented on python-flake8/linter
> +  python3 -m flake8 --append-config=$RULESET /usr/src/app
Не все комменты в ПР отработаны

2023-05-03 11:56 UTC, sgmdlt commented on python-flake8/linter
> -python3 -m flake8 --config=$OUTPUT_CONFIG /usr/src/app
В новом пр, если конфиг есть, то он будет приоритетным, если его нет, то дефолтный из образа

2023-05-03 11:56 UTC, sgmdlt commented on python-flake8/linter
> +OUTPUT_CONFIG=/tmp/setup.cfg
В новом пр она больше не используется

2023-05-03 11:56 UTC, sgmdlt commented on python-flake8/linter
> +#!/bin/sh
Убрал дублирование

2023-05-03 12:09 UTC, corsicanec82 commented on python-flake8/linter
> -python3 -m flake8 --config=$OUTPUT_CONFIG /usr/src/app
сейчас в коде я вижу только логику по добавлению конфига из практики в зависимости от наличия файла. Но полностью отсутствует логика по использованию дефолтного конфига который лежит в директории линтера $LINTER_DIR/setup.cfg

2023-05-03 12:35 UTC, sgmdlt commented on python-flake8/linter
> -python3 -m flake8 --config=$OUTPUT_CONFIG /usr/src/app
Насколько я понял потестировав локально, флейк по умолчанию подтянет ближайший к нему setup.cfg. То есть, если не передавать, то возьмет дефолтный. Но можно и явно указать брать его. Давай укажу явно.

2023-05-03 14:01 UTC, corsicanec82 commented on python-flake8/linter
> -python3 -m flake8 --config=$OUTPUT_CONFIG /usr/src/app
он подтянет да. Но беда в том что линтер запускается с директории /usr/src/app а не с /usr/src/linter потому базовый конфиг не подятентся. 
Смотри запуск как сделан в hexlet-exercise-kit. Именно так запускается на проде

2023-05-03 14:39 UTC, sgmdlt commented on python-flake8/linter
> -python3 -m flake8 --config=$OUTPUT_CONFIG /usr/src/app
Ага, я понял. Образ с линтером прокидывается вольюмом и линтер запускается из директории практики. И если там не будет конфига, то базовый не подтянется. Потому надо указать полный путь до базового конфига.

2023-05-04 14:22 UTC, sgmdlt commented on python-flake8/linter
> -python3 -m flake8 --config=$OUTPUT_CONFIG /usr/src/app
Ох, да, я понял теперь почему было изначально так. Думал что получится проще с новыми флагами флейка, но похоже придется вернуть все как было и только обновить версию флейка.

2023-05-04 14:28 UTC, corsicanec82 commented on python-flake8/linter
> -python3 -m flake8 --config=$OUTPUT_CONFIG /usr/src/app
так можно насколько я знаю. Просто нужно указать --config как было к базовому конфигу и плюс ещё --append-config в случае наличия доп конфига в практие

2023-05-04 16:40 UTC, sgmdlt commented on python-flake8/linter
> -python3 -m flake8 --config=$OUTPUT_CONFIG /usr/src/app
Да, вроде сработало. В доке было как-то неоднозначно написано

Provide a path to a config file that will be the only config file read and used. This will cause Flake8 to ignore all other config files that exist.

Но вроде два флага работают вместе

2023-05-05 06:28 UTC, corsicanec82 approved these changes

2023-05-05 06:29 UTC, merged