Typescript
Hexlet/hexlet-common-images pull request #70
Opened 2023-06-14 16:29 UTC by dzencot

2023-06-15 16:07 UTC, corsicanec82 requested changes
В целом каких то серьёзных проблем не вижу. 
Есть несколько небольших замечаний и вопросов (они в ревью)
Из важного: стоит поработать над варнингом (возможно скрыть его или использовать рекомендуемую версию). Так как он будет занимать полный вывод в практике и смущать пользователей
![2023-06-15_18-42-06](https://github.com/Hexlet/hexlet-common-images/assets/12639352/b89228ee-85d4-4730-af09-43bd90e42bfd)

Также порекомендую поставить отдельную задачу по обновлению версий зависимостей. Но тут лучше будет вначале обновить зависимости в базовом образе (кстати давно уже этого не было)

2023-06-15 16:07 UTC, corsicanec82 commented on eslint/tsconfig.eslint.json
> +  "include": ["/usr/src/**/*.jsx", "/usr/src/**/*.ts", "/usr/src/**/*.js"]
похоже мы расширения указываем в двух местах. Тут и в команде запуска линтера.
Нет возможности указывать только в одном месте, чтобы избежать дублирования?

2023-06-15 16:07 UTC, corsicanec82 commented on eslint/tsconfig.eslint.json
> +  "extends": "./tsconfig.json",
Нужны ли нам два файла конфигурации. 
Может описать конфиг в одном?

2023-06-16 08:31 UTC, dzencot commented on eslint/tsconfig.eslint.json
> +  "include": ["/usr/src/**/*.jsx", "/usr/src/**/*.ts", "/usr/src/**/*.js"]
Убрал из скрипта линтера, оставил только тут.

2023-06-16 08:36 UTC, dzencot commented
Поставил рекомендуемую версию, чтобы убрать варнинг

2023-06-16 11:11 UTC, corsicanec82 requested changes

2023-06-18 07:17 UTC, dzencot commented on eslint/tsconfig.json
> +  "include": ["/usr/src/**/*.jsx", "/usr/src/**/*.ts", "/usr/src/**/*.js"]
Поправил

2023-06-22 07:56 UTC, corsicanec82 commented on eslint/tsconfig.json
> +  "include": ["/usr/src/**/*.jsx", "/usr/src/**/*.ts", "/usr/src/**/*.js"]
Есть предложение как сделать немного проще и не завязываться наглухо на расположении /usr/src/linter
https://github.com/Hexlet/hexlet-common-images/pull/70

2023-06-22 09:40 UTC, corsicanec82 approved these changes

2023-06-22 09:42 UTC, merged