ruff
Hexlet/hexlet-common-images pull request #77
Opened 2024-11-06 12:25 UTC by sgmdlt

https://app.weeek.net/ws/613195/task/41621

2024-11-06 15:36 UTC, corsicanec82 requested changes
не хватает ещё изменений в воркфлоу для github actions

2024-11-06 15:36 UTC, corsicanec82 commented on sqlint/Dockerfile
> +FROM python:3.12-slim
sqllint явно не должен был быть в этом ПРе

2024-11-06 15:36 UTC, corsicanec82 commented on python-ruff/Dockerfile
> +FROM python:3.12-alpine
а почему версия не такая как в базовом образе?

2024-11-06 15:36 UTC, corsicanec82 commented on python-ruff/Dockerfile
> +COPY linter /linter
мы же уже в директории /linter
так что можно просто
copy linter . 
copy ruff.toml .

2024-11-06 15:36 UTC, corsicanec82 commented on python-ruff/ruff.toml
> +[lint.per-file-ignores]
в конфигурации для flake8 у нас были указаны определенный правила
https://github.com/Hexlet/hexlet-common-images/blob/main/python-flake8/setup.cfg
Дефолт у ruff совпадает с этим? Или решили что будем менять эти правила на дефолт от ruff?

2024-11-06 16:08 UTC, sgmdlt commented on python-ruff/linter
> +  $LINTER_HOME/lib/bin/ruff check /usr/src/app --config=$RULESET
нет. у него нет опции дополнить конфиг. так что два варианта, или дочерний конфиг должен дублировать опции из родительского, или поставить какой-то мержер томл файлов. 

кажется первый вариант проще и прозрачнее, т.к. сразу весь конфиг видно в репозитории

2024-11-06 16:11 UTC, sgmdlt commented on python-ruff/ruff.toml
> +[lint.per-file-ignores]
да, дефолт руфа почти повторяет флейк. я только добавил еще все правила в категории E. иначе базовая конфигурация руфа была мягче флейка и не включала часть правил.

2024-11-06 16:12 UTC, sgmdlt commented on python-ruff/Dockerfile
> +FROM python:3.12-alpine
да, верно, надо поменять на 3.13

2024-11-06 17:25 UTC, corsicanec82 commented on python-ruff/Dockerfile
> +VOLUME /var/tmp/.cache
проблема в том что кеш при запуске линтера на проде, впрочем как и в hexlet-exercise-kit будет писаться не сюда
Посмотри как подключается линтер в hexlet-exercise-kit
https://github.com/Hexlet/hexlet-exercise-kit/blob/2e55c5ece86327d196937a5e5540edc3d0d8930c/docker.mk#L126-L131
на проде аналогичный подход

2024-11-06 18:21 UTC, corsicanec82 commented on python-ruff/linter
> +  $LINTER_HOME/lib/bin/ruff check /usr/src/app --config=$RULESET
Ну так без оверайда плохо. Это приведёт к массовому дублированию по всем практикам одних и тех же конфигов. Представь если потом надо будет что-то поменять. Если не умеет, то нужно мержить тогда
Мы же кстати в других образах так и делаем. Вот например 
https://github.com/Hexlet/hexlet-common-images/blob/main/phpcs/linter#L14

Но вроде в доке написано что может. Как минимум в конфиге в /usr/src/app/ruff.toml можно указать 
extend = "/linter/ruff.toml" (в данном случае такой путь, в практиках extend = "../linter/ruff.toml")
И вот оверрайд из коробки

соотвественно в скрипте логика. Определяем путь к файлу конфига - глобальный конфиг. Если найден конфиг в директории практики то просто меняешь значение пути на этот файл.
И далее просто одна строка запуска с указанием пути к конфигу (уже определили выше)

2024-11-06 18:22 UTC, corsicanec82 commented on python-ruff/ruff.toml
> +[lint.per-file-ignores]
вроде же не всё так. Вот например у flake8 у нас было max-line-length = 80
а у ruff немного другой дефолт. Может это и норм. Просто уточняю согласован ли вопрос по проверкам

2024-11-07 10:03 UTC, sgmdlt commented on python-ruff/linter
> +  $LINTER_HOME/lib/bin/ruff check /usr/src/app --config=$RULESET
просмотрел опцию "extend". да, можно ей воспользоваться. вообще мы не часто в практиках оверрайдим базовые правила.

хотя сейчас посчитал и там 117 практик. но похоже это все "наследие" и конфигурации там почти пустые.

2024-11-07 10:17 UTC, corsicanec82 commented on python-ruff/linter
> +  $LINTER_HOME/lib/bin/ruff check /usr/src/app --config=$RULESET
>  вообще мы не часто в практиках оверрайдим базовые правила.

в ПР же добавляется работа с конфигом внутри практики. В таком случае, как и с остальными линтерами, логичнее использовать за основу базовый конфиг а в практиках если есть необходимость добавлять или изменять только то что нужно. Так не нужно будет дублировать основной конфиг, который можно при необходимости можно будет изменить в одном месте и актуализировать сразу для всех практик

2024-11-07 13:34 UTC, sgmdlt commented on python-ruff/ruff.toml
> +[lint.per-file-ignores]
Перепроверил конфиг, добавил нехватающих

2024-11-07 13:35 UTC, sgmdlt commented on python-ruff/Dockerfile
> +VOLUME /var/tmp/.cache
> как вариант эту опцию можно поместить в конфиг ruff.toml тогда будет одинаково работать и тут и в практиках

Не совсем понял про опцию. В чем отличие, между тем чтобы задавать в докерфайле?

2024-11-08 09:56 UTC, sgmdlt commented on python-ruff/Dockerfile
> +VOLUME /var/tmp/.cache
А, я понял почему я так делал. Потому что в common-images линтеры запускаются с вольюмами рид-онли. А почему кстати они рид-онли?

2024-11-08 10:20 UTC, sgmdlt commented on python-ruff/Dockerfile
> +VOLUME /var/tmp/.cache
lint-python-ruff:
	docker run --rm -t --read-only -v $(CURDIR)/python-ruff/app:/usr/src/app \
	  -v $(CURDIR)/python-ruff/linter:/linter/linter \
	  -v $(CURDIR)/python-ruff/ruff.toml:/linter/ruff.toml \
	  hexlet/common-python-ruff

2024-11-08 10:35 UTC, corsicanec82 commented on python-ruff/Dockerfile
> +VOLUME /var/tmp/.cache
> А почему кстати они рид-онли?

повторяют окружение на проде. Частично. Так как на проде в практиках есть места куда писать можно но тут принудительно они не указаны

2024-11-08 10:37 UTC, corsicanec82 commented on python-ruff/Dockerfile
> +VOLUME /var/tmp/.cache
но путь то тебе менять не надо было
cache-dir = "./.ruff-cache"
в практике возникнет ошибка, так как туда писать нельзя

2024-11-08 11:59 UTC, sgmdlt commented on python-ruff/Dockerfile
> +VOLUME /var/tmp/.cache
А, ты подразумевал оставить дефолт. Окей, оставил

2024-11-08 12:23 UTC, corsicanec82 commented on python-ruff/Dockerfile
> +VOLUME /var/tmp/.cache
да нет. Я же не писал что путь надо менять или исправлять. Написал что в конфиг перенести и всё.
то есть было у тебя /var/tmp/.cache вот и норм путь.
единственно стоит имя директории поправить на напрмиер .ruffcache
так как имя .cache универсально и может чем то уже использоваться

2024-11-08 13:56 UTC, sgmdlt commented on python-ruff/Dockerfile
> +VOLUME /var/tmp/.cache
>у ruff вроде дефолт для пути кеша в домашнюю директорию
а туда запись разрешена будет
https://gitlab.hexlet.io/hexlethq/hexlet-images/-/blob/main/base/Dockerfile?ref_type=heads#L32
тут тогда, можно оставить. 

Видимо не так прочитал.

Поменял на "/var/tmp/.ruff_cache"

2024-11-11 08:27 UTC, corsicanec82 commented
> не хватает ещё изменений в воркфлоу для github actions

@sgmdlt ещё этот коммент не отработан

2024-11-12 09:53 UTC, merged